spring.application.name = courses
courses.api.url = /api/v1

# Adding env file
spring.config.import = optional:file:.env[.properties]

# JWT Secret
jwt.secret.key = ${JWT_SECRET_KEY}

# Database config
spring.datasource.url = ${DATABASE_URL}
spring.datasource.username = ${DATABASE_USERNAME}
spring.datasource.password = ${DATABASE_PASSWORD}
spring.jpa.show-sql = true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.liquibase.change-log = classpath:/db.changelog/changelog-master.yaml

# Custom exception with HTTP status config
spring.web.error.include-message = always
spring.web.error.include-stacktrace = never
